.TH "my" "1" "" "Michele Bini"
.SH NAME
my \- Interactive Mythryl session
.SH SYNOPSIS
.PP
\fCmy\fP
.PP
\fCmy\fP [ \fImythryld options\fP ]
.SH DESCRIPTION
.PP
\fCmy\fP is a shorthand command for \fCmythryld\fP, and can be used to start an
interactive Mythryl session.
.SH OPTIONS
.PP
Please consult \fCmythryld\fP (1)
.SH EXAMPLE
.RS 3
.TP
\&\fCrlwrap my\fP
Starts mythryld with command line history and editing
provided by \fCrlwrap\fP (1).  \fCrlwrap\fP is not provided by the
mythryl compiler suite but can be installed separately.
.RE
.SH SEE ALSO
.PP
\fCmythryld\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


