.TH "mythryl-gtk-slave" "1" "" "Michele Bini"
.SH NAME
mythryl-gtk-slave \- GTK+ server for Mythryl applications
.SH SYNOPSIS
.PP
\fCmythryl-gtk-slave\fP
.SH DESCRIPTION
.PP
\fCmythryl-gtk-slave\fP is used by Mythryl applications to access GTK+ functionality.
.SH SEE ALSO
.PP
\fCmythryl\fP (1), \fCmythryld\fP (1), \fCbuild-an-executable-mythryl-heap-image\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


