.TH "mythryl-runtime-intel32" "1" "" "Michele Bini"
.SH NAME
mythryl-runtime-intel32 \- Runtime for Mythryl heap images
.SH SYNOPSIS
.PP
\fCmythryl-runtime-intel32\fP --shebang \fIheap file\fP
.SH DESCRIPTION
.PP
\fCmythryl-runtime-intel32\fP is a native binary necessary to execute
mythryl heap images, specifically those created by
\fCbuild-an-executable-mythryl-heap-image\fP.
.SH OPTIONS
.RS 3
.TP
\&\fC--shebang\fP \fIheap file\fP 
Execute \fIheap file\fP.
.RE
.SH SEE ALSO
.PP
\fCbuild-an-executable-mythryl-heap-image\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


