.TH "mythryl-ld" "1" "" "Michele Bini"
.SH NAME
mythryl-ld \- Mythryl compilers linking facility'
.SH DESCRIPTION
.PP
\fCmythryl-ld\fP is invoked by
\fCbuild-an-executable-mythryl-heap-image\fP to link together .compiled
and .lib.frozen files to produce an heap image file.
.SH SEE ALSO
.PP
\fCbuild-an-executable-mythryl-heap-image\fP (1),
\fCmythryl-runtime-intel32\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


