.TH "mythryld" "1" "" "Michele Bini"
.SH NAME
mythryld \- Execute Mythryl scripts
.SH SYNOPSIS
.PP
\fCmythryl\fP \fIscript\fP
.PP
\fC#!/usr/bin/mythryl\fP
.SH DESCRIPTION
.PP
The command \fCmythryl\fP executes Mythryl scripts,
compiling them on the fly.
.PP
It can be invoked by Mythryl scripts using a shebang
line, \fC#!/usr/bin/mythryl\fP, as the start of the script.
.PP
For an interactive Mythryl session invoke instead \fCmythryld\fP (1).
.PP
To compile mythryl source code into an executable file you can use
\fCbuild-an-executable-mythryl-heap-image\fP (1).
.SH SEE ALSO
.PP
\fCbuild-an-executable-mythryl-heap-image\fP (1), \fCmythryld\fP (1)
.SH AUTHOR
.PP
This page was written by Michele Bini.


